"""Ventilation-hole patterning on a finished helmet shell.

A *vent pattern* perforates the helmet wall over a localized surface patch so
the patient's head can breathe. We implement it by building a hex-packed array
of slender prism "cutters", each spanning the full wall thickness along the
local outward surface normal, then boolean-subtracting their union from the
shell. Each hole is a clean through-bore: its bore wall re-closes the shell,
so the result stays a watertight, winding-consistent closed solid.

This is an *additive* Week-4-permitted kernel primitive: it takes a finished,
watertight helmet shell (e.g. from :func:`kernel.operations.shell.build_shell`)
and returns a new watertight shell. It never mutates its input and contains
zero AI / no decisions — caller-supplied parameters in, deterministic geometry
out.

Cutter construction
-------------------
The patch is a circle of radius ``extent_mm`` centred at ``center_mm`` on the
shell. The local *outward* axis is the unit vector from the shell centroid
toward ``center_mm`` (an acceptable normal proxy per spec); ``(u, v)`` span the
tangent plane. Hex lattice centres are generated on the ``(u, v)`` plane on a
fixed, sorted integer grid (row/col), kept if within ``extent_mm`` of the
patch centre. Each retained centre gets one hexagonal prism whose axis is the
outward axis and whose half-length comfortably exceeds the wall thickness on
both sides, so the prism punches all the way through the wall.

Spacing formula
---------------
A regular hexagonal prism of circumradius ``r`` has cross-sectional area
``A_hole = (3*sqrt(3)/2) * r**2``. With hex (triangular) lattice spacing ``s``
between adjacent centres, each hole "owns" a hex Voronoi cell of area
``A_cell = (sqrt(3)/2) * s**2``. The open-area fraction is therefore
``phi = A_hole / A_cell = 3 * (r/s)**2``. Solving for the spacing given a
target ``phi``::

    r = feature_size_mm / 2                       # hole circumradius
    s = r * sqrt(3 / open_area_fraction)          # centre-to-centre spacing

Clamped so ``s`` is never below the hole circumdiameter (holes cannot overlap;
that would shred the lattice into a non-manifold sheet). Because the patch is
finite and the lattice integer-quantised, the realised open-area fraction is
approximate — this is acceptable per spec.

Sign of the volume change
-------------------------
``trimesh.Trimesh.volume`` for the hollow shell (an ``outer - inner`` manifold)
is the volume of the **solid wall material**. Every vent hole removes a plug of
wall material, so the vented shell's ``volume`` is *strictly smaller* than the
input's, and it decreases monotonically as ``open_area_fraction`` or
``feature_size_mm`` grows (more / larger holes ⇒ more material removed).

Determinism
-----------
The hex centres are generated by iterating a fixed integer grid in sorted
``(row, col)`` order, so the cutter union has identical topology across runs.
After the manifold3d boolean we convert back via
:func:`kernel.operations.shell._from_manifold`, which canonicalizes the
vertex / face ordering (lexsort + face rotation/sort). We never call
``trimesh.fix_normals`` on the boolean output (per the repo determinism note);
``fix_normals`` *is* used on the prism cutters we construct ourselves, which is
empirically deterministic for the pinned trimesh version. Identical arguments
therefore produce a byte-identical STL export.
"""

from __future__ import annotations

import logging

import numpy as np
import trimesh

from kernel.errors import GeometryError
from kernel.operations.shell import _from_manifold, _to_manifold

logger = logging.getLogger(__name__)

# The only ventilation pattern implemented this week.
_VALID_PATTERNS = ("hex_lattice",)

# Number of sides of each cutter prism's cross-section. A hexagon is a tight
# polygonal approximation of a round hole and tiles the hex lattice naturally.
_PRISM_SIDES = 6

# Half-length multiplier: each prism extends this many wall-thicknesses beyond
# the shell on each side of the patch so it cleanly spans (and over-shoots) the
# wall regardless of local curvature. Generous over-shoot keeps the through-cut
# robust without affecting the (canonicalized) result.
_PRISM_OVERSHOOT_MM = 30.0

# Geometric constants for the hex-lattice area bookkeeping.
_HEX_AREA_COEF = 3.0 * np.sqrt(3.0) / 2.0  # regular-hexagon area / circumradius^2
_TRI_LATTICE_COEF = np.sqrt(3.0) / 2.0  # triangular-lattice cell area / spacing^2


def _local_outward_frame(
    shell_mesh: trimesh.Trimesh, center: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return an orthonormal frame ``(u, v, axis)`` for the vent patch.

    ``axis`` is the unit vector from the shell centroid to ``center`` (the
    local "outward", head-away direction — an acceptable surface-normal proxy
    per spec). ``u`` and ``v`` span the tangent plane. The frame is derived
    deterministically from the geometry with a fixed tie-breaking reference
    (mirrors ``kernel.primitives.relief._local_outward_axis``).
    """
    axis = center - np.asarray(shell_mesh.centroid, dtype=np.float64)
    norm = float(np.linalg.norm(axis))
    if norm < 1e-9:
        raise GeometryError(
            "vent center coincides with the shell centroid; " "cannot derive an outward axis",
            context={"center_mm": center.tolist()},
        )
    axis = axis / norm
    reference = np.array([0.0, 0.0, 1.0]) if abs(axis[2]) < 0.9 else np.array([1.0, 0.0, 0.0])
    u = np.cross(axis, reference)
    u = u / np.linalg.norm(u)
    v = np.cross(axis, u)
    return u, v, axis


def _hex_lattice_centers(
    extent_mm: float,
    spacing_mm: float,
) -> np.ndarray:
    """Hex (triangular) lattice of 2-D ``(u, v)`` offsets within the patch.

    Centres are produced by scanning a bounded integer grid in a fixed,
    sorted ``(row, col)`` order (determinism, invariant #2). Row ``j`` is at
    height ``j * row_pitch`` (``row_pitch = spacing * sqrt(3)/2``) and odd rows
    are shifted by half a spacing — the classic A2 / triangular packing. Only
    centres within ``extent_mm`` of the patch centre are kept.
    """
    row_pitch = spacing_mm * _TRI_LATTICE_COEF
    n_rows = int(np.floor(extent_mm / row_pitch)) + 1
    n_cols = int(np.floor(extent_mm / spacing_mm)) + 1

    offsets: list[tuple[float, float]] = []
    # Sorted iteration: j ascending, then i ascending — fully deterministic.
    for j in range(-n_rows, n_rows + 1):
        y = j * row_pitch
        x_shift = 0.5 * spacing_mm if (j % 2) != 0 else 0.0
        for i in range(-n_cols, n_cols + 1):
            x = i * spacing_mm + x_shift
            if x * x + y * y <= extent_mm * extent_mm:
                offsets.append((x, y))

    if not offsets:  # pragma: no cover — extent_mm > 0 always yields the origin
        raise GeometryError(
            "hex lattice produced no vent centres",
            context={"extent_mm": float(extent_mm), "spacing_mm": float(spacing_mm)},
        )
    return np.array(sorted(offsets), dtype=np.float64)


def _build_hex_prism(
    center_pt: np.ndarray,
    circumradius_mm: float,
    u: np.ndarray,
    v: np.ndarray,
    axis: np.ndarray,
    half_len_mm: float,
) -> trimesh.Trimesh:
    """Build one closed hexagonal prism cutter.

    The hexagon lies in the ``(u, v)`` plane (fixed vertex angles, so the
    topology is identical for every hole) and is extruded ``±half_len_mm``
    along ``axis``. Returns a watertight, winding-consistent solid.
    """
    angles = np.linspace(0.0, 2.0 * np.pi, _PRISM_SIDES, endpoint=False)
    ring = np.array(
        [circumradius_mm * (np.cos(a) * u + np.sin(a) * v) for a in angles],
        dtype=np.float64,
    )
    top = center_pt + ring + axis * half_len_mm
    bot = center_pt + ring - axis * half_len_mm
    verts = np.vstack([top, bot])

    n = _PRISM_SIDES
    faces: list[list[int]] = []
    # Top cap (fan), outward normal along +axis.
    for k in range(1, n - 1):
        faces.append([0, k, k + 1])
    # Bottom cap (fan), reversed winding (normal along -axis).
    for k in range(1, n - 1):
        faces.append([n, n + k + 1, n + k])
    # Side quads joining top ring -> bottom ring.
    for k in range(n):
        k1 = (k + 1) % n
        faces.append([k, n + k, n + k1])
        faces.append([k, n + k1, k1])

    prism = trimesh.Trimesh(vertices=verts, faces=np.array(faces, dtype=np.int64), process=False)
    # fix_normals is empirically deterministic for the pinned trimesh version
    # on a mesh we construct ourselves (same rationale as
    # kernel/operations/trim.py and kernel/primitives/relief.py). It is NOT
    # applied to the boolean output.
    prism.fix_normals()
    return prism


def _validate_args(
    helmet_mesh: trimesh.Trimesh,
    pattern: str,
    extent_mm: float,
    open_area_fraction: float,
    feature_size_mm: float,
) -> None:
    """Reject malformed inputs before touching geometry (invariant #6)."""
    if not helmet_mesh.is_volume:
        raise GeometryError(
            "helmet input to apply_vent_pattern is not a valid volume",
            context={
                "is_winding_consistent": bool(helmet_mesh.is_winding_consistent),
                "is_watertight": bool(helmet_mesh.is_watertight),
            },
        )
    if pattern not in _VALID_PATTERNS:
        raise GeometryError(
            f"unknown vent pattern {pattern!r}; this week supports only " f"{_VALID_PATTERNS}",
            context={"pattern": pattern},
        )
    if extent_mm <= 0.0:
        raise GeometryError(f"vent extent_mm must be > 0, got {extent_mm}")
    if feature_size_mm <= 0.0:
        raise GeometryError(f"vent feature_size_mm must be > 0, got {feature_size_mm}")
    if not (0.0 < open_area_fraction < 0.9):
        raise GeometryError(
            f"vent open_area_fraction must be in (0, 0.9), got {open_area_fraction}"
        )


def apply_vent_pattern(
    helmet_mesh: trimesh.Trimesh,
    center_mm: tuple[float, float, float],
    extent_mm: float,
    pattern: str = "hex_lattice",
    open_area_fraction: float = 0.18,
    feature_size_mm: float = 6.0,
) -> trimesh.Trimesh:
    """Punch a ventilation-hole pattern through the helmet wall.

    Args:
        helmet_mesh: A watertight, winding-consistent helmet shell in the
            canonical reference frame (origin between the ear canals, +X
            patient right, +Y anterior, +Z superior). Not mutated.
        center_mm: ``(x, y, z)`` of the vent patch centre, in mm, in the
            canonical frame. Should lie on / near the helmet surface; the
            holes land on the surface patch around it.
        extent_mm: Radius of the circular vent patch, in mm. Must be > 0.
        pattern: Lattice pattern. Only ``"hex_lattice"`` is supported this
            week; any other value raises ``GeometryError``.
        open_area_fraction: Target fraction of the patch area removed as
            holes, in ``(0, 0.9)``. Drives the lattice spacing (see module
            docstring); the realised fraction is approximate.
        feature_size_mm: Hole size — the circumdiameter of each hexagonal
            hole, in mm. Must be > 0. Larger ⇒ bigger holes ⇒ more material
            removed.

    Returns:
        A new ``trimesh.Trimesh`` — the vented shell, watertight and
        winding-consistent. Its ``volume`` (solid wall material) is strictly
        smaller than the input's because each hole removes a plug of wall.

    Raises:
        kernel.errors.GeometryError: if the input is not a valid volume, the
            pattern is unsupported, the arguments are out of range, or the
            boolean produced empty / non-watertight geometry.
    """
    _validate_args(helmet_mesh, pattern, extent_mm, open_area_fraction, feature_size_mm)

    center = np.array(center_mm, dtype=np.float64)
    u, v, axis = _local_outward_frame(helmet_mesh, center)

    # Hole circumradius and lattice spacing from the open-area model:
    #   phi = A_hex / A_cell = 3 * (r / s)^2  =>  s = r * sqrt(3 / phi).
    circumradius_mm = feature_size_mm / 2.0
    spacing_mm = circumradius_mm * float(np.sqrt(3.0 / open_area_fraction))
    # Holes must not overlap (an overlapping lattice would dissolve the wall
    # into a non-manifold sheet). The tightest non-overlapping packing puts
    # centres one circumdiameter apart; clamp to that.
    min_spacing_mm = 2.0 * circumradius_mm
    if spacing_mm < min_spacing_mm:
        spacing_mm = min_spacing_mm

    offsets_uv = _hex_lattice_centers(extent_mm, spacing_mm)

    # Half-length: span the wall plus a generous over-shoot on both sides so
    # every prism fully perforates regardless of local curvature.
    half_len_mm = _PRISM_OVERSHOOT_MM

    # Union all hexagonal prism cutters via manifold3d, then subtract once.
    helmet_m = _to_manifold(helmet_mesh)
    cutter_union: object | None = None
    for off_u, off_v in offsets_uv:
        pt = center + off_u * u + off_v * v
        prism = _build_hex_prism(pt, circumradius_mm, u, v, axis, half_len_mm)
        if not prism.is_volume:  # pragma: no cover — constructed deterministically
            raise GeometryError(
                "constructed vent prism is not a valid volume",
                context={
                    "is_watertight": bool(prism.is_watertight),
                    "is_winding_consistent": bool(prism.is_winding_consistent),
                },
            )
        prism_m = _to_manifold(prism)
        cutter_union = prism_m if cutter_union is None else cutter_union + prism_m

    if cutter_union is None:  # pragma: no cover — lattice always has >=1 centre
        raise GeometryError(
            "vent pattern produced no cutters",
            context={"center_mm": center.tolist(), "extent_mm": float(extent_mm)},
        )

    vented_m = helmet_m - cutter_union
    if vented_m.is_empty():
        raise GeometryError(
            "vent boolean subtract produced an empty manifold",
            context={
                "center_mm": center.tolist(),
                "extent_mm": float(extent_mm),
                "open_area_fraction": float(open_area_fraction),
                "feature_size_mm": float(feature_size_mm),
            },
        )

    vented = _from_manifold(vented_m)

    # Final invariant gate: never let broken geometry escape the kernel
    # (invariant #6). A vent hole keeps the shell closed because each bore
    # wall re-seals it; if that did not hold, the result would not be
    # watertight and we must raise rather than return it.
    if not vented.is_winding_consistent or not vented.is_watertight:
        raise GeometryError(
            "vent boolean produced non-watertight / non-winding-consistent " "geometry",
            context={
                "center_mm": center.tolist(),
                "extent_mm": float(extent_mm),
                "open_area_fraction": float(open_area_fraction),
                "feature_size_mm": float(feature_size_mm),
                "is_watertight": bool(vented.is_watertight),
                "is_winding_consistent": bool(vented.is_winding_consistent),
            },
        )

    logger.debug(
        "apply_vent_pattern: input_v=%d holes=%d output_v=%d spacing_mm=%.3f",
        len(helmet_mesh.vertices),
        len(offsets_uv),
        len(vented.vertices),
        spacing_mm,
    )
    return vented
